// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWQ9cVsVjwqdBpv6T7YRWpM5qBhlQ7DY0',
    appId: '1:722652385293:web:83d3d609477a172a604544',
    messagingSenderId: '722652385293',
    projectId: 'helminal',
    authDomain: 'helminal.firebaseapp.com',
    storageBucket: 'helminal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsEtrdxfTYHr3n-k6usclUAxhCqrWqXNM',
    appId: '1:722652385293:android:698a19a1fa9a6037604544',
    messagingSenderId: '722652385293',
    projectId: 'helminal',
    storageBucket: 'helminal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnRUVI1IS-A1t6BScEj-xdrVfulx3GQE4',
    appId: '1:722652385293:ios:3d16b475e0222c87604544',
    messagingSenderId: '722652385293',
    projectId: 'helminal',
    storageBucket: 'helminal.appspot.com',
    iosBundleId: 'com.example.helminal',
  );
}
